

env:
  PROJECT_PATH: '/home/george/PycharmProjects/open_cv_take_bone_txt'
  THRESHOLD_OF_IMAGE_PRC: 5
  THRESHOLD_OF_TXTBOXES_LENGTH: 0
  THRESHOLD_OF_TXT_PRC: 5

mongo:
  host: 'localhost'
  port: 27017
  user: 'bone'
  password: 'bonepwd'
  db_name: 'bonedb'
  collection_name: 'img_texts'

#============ DEBUG ===============
debug_env:
  START_AT: "00:13:02.920000"
  END_AT: "00:13:03.920000"
  # START_AT: "00:00:00.920000"
  # END_AT: "00:00:01.920000"