

env:
  THRESHOLD_OF_IMAGE_PRC: 20
  THRESHOLD_OF_TXTBOXES_LENGTH: 0
  THRESHOLD_OF_TXT_PRC: 5
  MIN_NUMBER_OF_DATA_TABLE_LINES: 4

mongo:
  host: 'localhost'
  port: 27017
  user: 'bone'
  password: 'bonepwd'
  db_name: 'bonedb'
  collection_name: 'img_texts'

#============ DEBUG ===============
debug_env:
#  START_AT: "00:13:03.80000"
#  END_AT: "00:17:23.920000"
   START_AT: "00:00:00.00000"
   END_AT: "00:20:01.920000"