# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: bone
      MONGO_INITDB_ROOT_PASSWORD: bonepwd

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bone
      ME_CONFIG_MONGODB_ADMINPASSWORD: bonepwd
      ME_CONFIG_MONGODB_URL: mongodb://bone:bonepwd@mongo:27017/